#!/bin/bash
# IndexNow submission.
# GENERATED by scripts/build-indexnow.mjs from sitemap.xml — do not edit by hand.
# Regenerate with: node scripts/build-indexnow.mjs
# Participating engines: Bing, Yandex, Naver, Seznam, Yep. Google does NOT use IndexNow.
#
# Usage:
#   bash submit-indexnow.sh                  submit every canonical URL
#   bash submit-indexnow.sh URL [URL ...]    submit only the URLs given
#
# IndexNow is a "this changed" signal, not a heartbeat. Announcing all 44 URLs on
# every commit reads as noise to the receiving engines, so CI passes the changed
# URLs on push and only re-announces the full list on the weekly run.

set -euo pipefail

INDEXNOW_KEY="f1f454b32a9646baba021f7af031df07"
HOST="purposelabstudio.com"
KEY_LOCATION="https://${HOST}/${INDEXNOW_KEY}.txt"

ALL_URLS=(
  "https://${HOST}/"
  "https://${HOST}/about/"
  "https://${HOST}/apps/"
  "https://${HOST}/best-free-baby-sleep-app/"
  "https://${HOST}/best-free-blood-pressure-app/"
  "https://${HOST}/best-free-journal-app/"
  "https://${HOST}/best-free-water-reminder-app/"
  "https://${HOST}/blog/"
  "https://${HOST}/blog/baby-wont-sleep-through-night/"
  "https://${HOST}/blog/brown-noise-vs-white-noise-vs-pink-noise/"
  "https://${HOST}/blog/build-a-second-brain-on-whatsapp/"
  "https://${HOST}/blog/daily-journal-vs-mood-tracker-why-you-need-both/"
  "https://${HOST}/blog/how-much-water-should-i-drink-daily/"
  "https://${HOST}/blog/how-to-lower-blood-pressure-immediately-at-home/"
  "https://${HOST}/blog/how-to-lower-blood-pressure-naturally/"
  "https://${HOST}/blog/how-to-track-blood-pressure-at-home/"
  "https://${HOST}/blog/journaling-prompts-for-anxiety/"
  "https://${HOST}/blog/journaling-prompts-for-overthinking/"
  "https://${HOST}/blog/journaling-prompts-for-self-discovery/"
  "https://${HOST}/blog/message-yourself-on-whatsapp-not-showing/"
  "https://${HOST}/blog/normal-blood-pressure-by-age/"
  "https://${HOST}/blog/printable-blood-pressure-log/"
  "https://${HOST}/blog/stop-messaging-yourself-on-whatsapp/"
  "https://${HOST}/blog/water-reminder-app-without-ads/"
  "https://${HOST}/blog/what-happens-if-someone-reads-your-journal/"
  "https://${HOST}/blog/white-noise-baby-sleep-science/"
  "https://${HOST}/blog/why-journaling-apps-make-you-feel-guilty/"
  "https://${HOST}/blog/why-journaling-fails-and-how-to-stick-with-it/"
  "https://${HOST}/blog/why-water-apps-are-full-of-ads/"
  "https://${HOST}/bplog/"
  "https://${HOST}/bplog/printable-log/"
  "https://${HOST}/crumbs/"
  "https://${HOST}/folio/"
  "https://${HOST}/folio/diary/"
  "https://${HOST}/folio/journal/"
  "https://${HOST}/folio/try/"
  "https://${HOST}/hushly/"
  "https://${HOST}/support/"
  "https://${HOST}/tools/"
  "https://${HOST}/tools/blood-pressure-checker/"
  "https://${HOST}/tools/journal-prompt-generator/"
  "https://${HOST}/tools/water-intake-calculator/"
  "https://${HOST}/tools/white-noise-player/"
  "https://${HOST}/waterwise/"
)

if [ "$#" -gt 0 ]; then
  URLS=("$@")
else
  URLS=("${ALL_URLS[@]}")
fi

# URLs contain no quotes or backslashes, so simple JSON assembly is safe here.
URL_JSON=$(printf '"%s",' "${URLS[@]}" | sed 's/,$//')
PAYLOAD="{\"host\":\"${HOST}\",\"key\":\"${INDEXNOW_KEY}\",\"keyLocation\":\"${KEY_LOCATION}\",\"urlList\":[${URL_JSON}]}"

echo "Submitting ${#URLS[@]} URLs to IndexNow..."
curl -sS -X POST "https://api.indexnow.org/IndexNow" \
  -H "Content-Type: application/json; charset=utf-8" \
  -d "${PAYLOAD}" -w '\nHTTP %{http_code}\n'
